In [ ]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/content/DYCD_after-school_programs__Neighborhood_Development_Area__NDA__Family_Support.csv')

In [3]:
df.head()

,PROGRAM TYPE,PROGRAM,SITE NAME,BOROUGH / COMMUNITY,AGENCY,Contact Number,Grade Level / Age Group,Location 1,Postcode,Latitude,Longitude,Community Board,Community Council,Census Tract,BIN,BBL,NTA
0,"Reading & Writing,NDA Programs,Family Literacy",Adolescent Literacy,K 533- School for Democracy and Leadership 600...,Brooklyn,CAMBA,718.282.5575,grades 6 to 8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"After-School Programs,NDA Programs,Youth Educa...",High-School Aged Youth,Voyagees Prepatory High School,Queens,Central Brooklyn Economic Development Corporation,(718) 592-5757,High School,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"Family Support,NDA Programs",Housing,AIDS Center of Queens County Jamaica Site,Queens,St. Luke A.M.E Church,(718) 896-2500,Adults,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"Immigration Services,Immigrant Support Services",Legal Services,"Sanctuary for Families, Inc. (Manhattan)","Manhattan,Bronx,Queens,Staten Island, Brooklyn","Sanctuary for Families, Inc.",212.349.6009 ext. 264,All Ages,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"Immigration Services,Immigrant Support Services",Legal Services,Family Justice Centers in Queens and Brooklyn,"Manhattan,Bronx,Queens,Staten Island, Brooklyn","Sanctuary for Families, Inc.",212.349.6009 ext. 264,All Ages,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.shape

(464, 17)

In [6]:
df

,PROGRAM TYPE,PROGRAM,SITE NAME,BOROUGH / COMMUNITY,AGENCY,Contact Number,Grade Level / Age Group,Location 1,Postcode,Latitude,Longitude,Community Board,Community Council,Census Tract,BIN,BBL,NTA
0,"Reading & Writing,NDA Programs,Family Literacy",Adolescent Literacy,K 533- School for Democracy and Leadership 600...,Brooklyn,CAMBA,718.282.5575,grades 6 to 8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"After-School Programs,NDA Programs,Youth Educa...",High-School Aged Youth,Voyagees Prepatory High School,Queens,Central Brooklyn Economic Development Corporation,(718) 592-5757,High School,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"Family Support,NDA Programs",Housing,AIDS Center of Queens County Jamaica Site,Queens,St. Luke A.M.E Church,(718) 896-2500,Adults,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"Immigration Services,Immigrant Support Services",Legal Services,"Sanctuary for Families, Inc. (Manhattan)","Manhattan,Bronx,Queens,Staten Island, Brooklyn","Sanctuary for Families, Inc.",212.349.6009 ext. 264,All Ages,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"Immigration Services,Immigrant Support Services",Legal Services,Family Justice Centers in Queens and Brooklyn,"Manhattan,Bronx,Queens,Staten Island, Brooklyn","Sanctuary for Families, Inc.",212.349.6009 ext. 264,All Ages,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
459,"Reading & Writing,NDA Programs,Family Literacy",Family Literacy,Edith and Carl Marks Jewish Community House of...,Brooklyn,Edith and Carl Marks Jewish Community House of...,718-943-6325,A parent 16 Years Old or Older,"7802 Bay Parkway\nBrooklyn, NEW YORK 11214\n(4...",11214.0,40.606369,-73.989235,11.0,44.0,270.0,3162352.0,3.062640e+09,Bensonhurst West ...
460,"Reading & Writing,NDA Programs,Family Literacy",Adolescent Literacy,JHS 22- Jordan L Mott School,Bronx,Supportive Childrens Advocacy Network (SCAN),212.683.2522,grades 6 to 8,"270 167th Street\nBronx, NEW YORK 10456\n(40.8...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
461,"Reading & Writing,NDA Programs,English Languag...",Adult Literacy,Washington Houses Community Center,Manhattan,Union Settlement Association,(212) 828-6298,16+,"1775 3rd Avenue\nManhattan, NEW YORK 10029\n(4...",10029.0,40.786574,-73.948303,11.0,8.0,15602.0,1079203.0,1.016470e+09,East Harlem South ...
462,"NDA Programs,Senior Programs,Older Adult Program",Seniors,Highbridge Gardens,Bronx,Children's Aid Society/East Harlem Center,(718) 542-0006,Seniors,"1145 University Avenue\nBronx, NEW YORK 10452\...",10452.0,40.837077,-73.928282,4.0,16.0,193.0,2095219.0,2.025270e+09,Highbridge ...
463,"Family Support,NDA Programs",Housing,Harlem Justice Center,New York,The Urban Assembly School for Law and Justice,(212) 473-8090,Adults,"170 121st Street\nNew York, NEW YORK 10035\n(4...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
import requests
from io import StringIO

url = ""
headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}
req = requests.get(url, headers=headers)
data = StringIO(req.text)

pd.read_csv(data)

In [ ]:
df = pd.read_csv('/content/DYCD_after-school_programs__Neighborhood_Development_Area__NDA__Family_Support.csv', sep = '/t', names=['',''])

In [7]:
from google.colab import files

df.to_csv('data.csv', index=False)
files.download('data.csv')